### ISSUE TITLE
Change closeondateselect true by false

### ISSUE THREAD

**Issue by farwarx** [Smile-SA/redmine_datetime_custom_field#7]
Hello,
By default, the closeondateselect is on true.
But can you change it to false?
Or by add a choice on custom field :)

Quick fix:
lib/datetime_custom_field_application_helper_patch.rb
    a = javascript_tag("var datetimepickerOptions={format: 'Y-m-d H:i', closeOnDateSelect:true };")
to
    a = javascript_tag("var datetimepickerOptions={format: 'Y-m-d H:i', closeOnDateSelect:false };")

**Comment by Utopism** [comment]
Hello, yes this is a fair request !

**Comment by Utopism** [comment]
Done in V1.0.4
