### ISSUE TITLE
New Polish locale

### ISSUE THREAD

**Issue by bkaczynski** [Smile-SA/redmine_datetime_custom_field#8]
I want add polish translation and date format to this plugin. I've created pl.yml file to $REDMINE_ROOT/plugins/redmine_datetime_custom_field/config/locales directory but I am not sure of content of this file. Additionally I've deleted rest of files.
I tested various solutions:
- clear cache in browser and in application (rake tmp:cache:clear),
- restart web server
- even correct permission to pl.yml file
but I still see English locale. Language in Redmine is polish also.

I found this file: https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/pl.yml but I am not sure how to use it in this case

The goal is achieve the format:
for e.g. instead of: Thu, 11 Jun 2020 15:23:00 +0000 should be just: 11.06.2020 15:23 (dd.mm.yyyy hh:mm format)

**Comment by Utopism** [comment]
Hi, if you give me the translation for :
`label_datetime: "DateTime"`
I will add it in the plugin.

**Comment by bkaczynski** [comment]
"DateTime" in polish means: "DataCzas"

**Comment by Utopism** [comment]
About localization of DateTime in Polish, where do you want to see the **dd.mm.yyyy hh:mm** format ?
The plugin is configured to use and display this format by default.

**Comment by bkaczynski** [comment]
Issue list.

**Comment by Utopism** [comment]
Just tested and you're right locale is not in the international format :
![image](https://user-images.githubusercontent.com/540464/84420923-1125b600-ac1b-11ea-9e5e-e2c46e38a461.png)

**Comment by bkaczynski** [comment]
Date picker is also in English only.

**Comment by bkaczynski** [comment]
Damn I've closed.
Date picker is also only in English.

**Comment by bkaczynski** [comment]
Damn I've closed.
Date picker is also only in English.

**Comment by Utopism** [comment]
Hi, new V1.0.3 fixes this.
